---
# tasks file for jira

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags: jira

- include: CentOS.yml
  when: ansible_distribution == "CentOS"
  tags: jira

- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags: jira

- name: Create JIRA group
  group: name=jira state=present
  tags: jira

- name: Create JIRA user
  user: >
    name=jira
    group=jira
    comment="JIRA user"
    home={{ jira_home_dir }}
    shell=/bin/bash
    createhome=no
  tags: jira

- name: Create JIRA working directory
  file: >
    path={{ jira_work_dir }}
    owner=root
    group=root
    mode=0755
    state=directory
  tags: jira

- name: Create JIRA install directory
  file: >
    path={{ jira_install_dir }}
    owner=jira
    group=jira
    mode=0755
    state=directory
  tags: jira

- name: Create JIRA home directory
  file: >
    path={{ jira_home_dir }}
    owner=jira
    group=jira
    mode=0755
    state=directory
  tags: jira

- name: Download JIRA
  get_url: >
    url={{ jira_download_url }}
    dest={{ jira_work_dir }}/{{ jira_archive }}
    sha256sum={{ jira_archive_sha256sum }}
  tags: jira

- name: Extract JIRA to install directory
  unarchive: >
    src={{ jira_work_dir }}/{{ jira_archive }}
    dest={{ jira_install_dir }}
    owner=jira
    group=jira
    mode=0755
    copy=no
    creates={{ jira_install_dir }}/atlassian-jira-{{ jira_version }}-standalone
  tags: jira

- name: Create symlink for current version
  file: >
    src={{ jira_install_dir }}/atlassian-jira-{{ jira_version }}-standalone
    dest={{ jira_install_dir }}/current
    state=link
  tags: jira

- name: Set JIRA environment settings
  template: >
    src=setenv.sh.j2
    dest={{ jira_install_dir }}/atlassian-jira-{{ jira_version }}-standalone/bin/setenv.sh
    owner=jira
    group=jira
    mode=0755
  notify: restart jira
  tags: jira

- name: Create JIRA init script
  template: >
    src=jira.j2
    dest=/etc/init.d/jira
    owner=root
    group=root
    mode=0755
  tags: jira

- name: Ensure JIRA service is started and enabled on boot
  service: >
    name=jira
    state=started
    pattern='/usr/bin/java -Djava.util.logging.config.file=/opt/atlassian/jira/atlassian-jira-{{ jira_version }}-standalone/conf/logging.properties'
    enabled=yes
  tags: jira
